### ISSUE TITLE
Ember App Kit?

### ISSUE THREAD

**Issue by macavon** [yeoman/generator-ember#102]
You probably noticed the bit in the Ember 1.0 release announcement, where it says that Ember Application Kit (EAK) 'will eventually become the core of official Ember tools'. There's also an enigmatic sentence in the EAK readme about it being used as  'the base scaffolding for generators built on for Ember applications, including [...] generator-ember'.

Are there plans to harmonize `generator-ember` and EAK, or to use the application kit as the basis of the gnerator's scaffolding, or would it be a good idea to create a separate `generator-eak` for people who want to use EAK with Yeoman's workflow?

I realize this may be an impertinent question, but there seems to be a risk that `generator-ember` may become irrelevant if the Ember docs are pointing people at EAK at some point in the future.

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
