### ISSUE TITLE
Sync Usemin usage with generator-webapp

### ISSUE THREAD

**Issue by stephenplusplus** [yeoman/generator-ember#103]
*Inspiration:
https://gist.github.com/josemota/6424699*

Like the [`generator-webapp` Gruntfile](https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L267-282), I think this generator should comment out the `cssmin` task, preferring Usemin blocks.

In addition to that, it would also need to write the block to `index.html` specifying alternate search paths, such as the opening block from this snippet:

```html
<!-- build:css({.tmp,app}) styles/main.css -->
<link rel="stylesheet" href="bower_components/bootstrap-sass/bootstrap-2.3.2.css">
<link rel="stylesheet" href="styles/style.css">
<!-- endbuild -->
```

These things should clear up the issue from gist bug report.

// @josemota

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
