### ISSUE TITLE
Replace development environment with production ready version of Ember

### ISSUE THREAD

**Issue by josemota** [yeoman/generator-ember#110]
I was thinking about the build process of an app using Ember and Yeoman and realized there needs to be a subtask under `build` that needs to swap the development version of Ember with its production counterbuild which strips assertions and other development helpers away.

I'm still not at par with how I should accomplish this, but if anyone wants to take a stab, go ahead!

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
