### ISSUE TITLE
Taking the generator to the next level

### ISSUE THREAD

**Issue by fayimora** [yeoman/generator-ember#144]
This gist is a detailed list of tasks that should be completed to get the [Yeoman Ember generator](http://github.com/yeoman/generator-ember) 'to the next level'.

If I have to get this all done myself, it'll take a long time because I'm busy at uni right now so please if you are interested in tackling any of the problems below(I hope you are :smiley:), just indicate so I tag you on it and we don't duplicate efforts. 

These tasks **must** to be completed in order. So the *General Cleanup* must be completed before *Enhancements*. That should keep problems to a bare minimum. I will **not** merge and enhancement PRs until we clean house :smile: 

1. [ ] **General Cleanup**
These tasks MUST **not** change the generator's functionality!

  1. [ ] Refactor and write more reasonable tests (@smackesey)

  2. [ ] Refactor common code in `<generator>/index.js` into a common file that will be included in all generators.

  3. [ ] Cleanup Gruntfile. It's currently very cluttered. Ideally we should move all tasks into tasks/options/<task>.js

  4. [ ] Refactor Coffeescript support. We duplicate js templates for Coffeescript. Maybe there's a better way to do this?

  5. [ ] ...

2. [ ] **Enhancements**
Cant wait to get to this part! Unfortunately, some changes in this section will not be backwards compatible.

  1. [ ] Rewrite generators. The current generators are nice but IMO, a little messy. We should keep them simple!

    - [ ] Remove sample code generated. I was thinking maybe we add an `example` generator with a todoapp
    - [ ] Not everything is CRUD. The generators assume everything is crud. We could move the crud behavior to flags
    - [ ] ...
  
  2. [ ] Improve testing

    - [ ] Karma doen't really run when templates are changed
    - [ ] Qunit is the recommended testing library for ember apps.Time to integrate it aswell

  3. [ ] Use the [ember-jj-abrams-resolver](https://github.com/stefanpenner/ember-jj-abrams-resolver), [ES6 Module Transpiler](https://github.com/square/es6-module-transpiler) and its [grunt-plugin](https://github.com/joefiorini/grunt-es6-module-transpiler) to introduce ES6 modules :smile:

  4. [ ] Get rid of ruby dependency.

  5. [ ] Add new `environment` folder to contain configuration files for different environments.

I'll update the list with a few more tasks as time goes by.

Cheers,
Fayi

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
