### ISSUE TITLE
Reloading is very slow

### ISSUE THREAD

**Issue by kraftwer1** [yeoman/generator-ember#149]
I have just upgraded my project to 0.7.1 (the last version was around 5 months old), but the reloading is now so slow that it's almost impossible to work.

On the first look I couldn't find out what part is slow, I changed a javascript file (I used it without `-coffee`).

Does anybody know what piece of Yeoman made the whole process so slow in the last couple of months?

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
