### ISSUE TITLE
Setup system to replace variables inside compiled file depending on grunt environment

### ISSUE THREAD

**Issue by borisrorsvort** [yeoman/generator-ember#153]
I've looked at different tools like:

https://github.com/logankoester/grunt-environment
https://github.com/jsoverson/grunt-env
https://github.com/outaTiME/grunt-config

I don't quite see how can you set/get for instance different adapter url in your router.js depending on some grunt/node environment.

Can we think about something/tasks that could do that?

I think [this](http://loutilities.wordpress.com/2013/08/29/grunt-targeted-environment-builds-for-node-js-jshint-closure-compiler/) could be a great starting point

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

This generator has been missing a maintainer for a long time and the Ember community is strongly behind ember-cli.
