### ISSUE TITLE
Integration test scaffolding doesn't get generated

### ISSUE THREAD

**Issue by knownasilya** [yeoman/generator-ember#166]
In `app/templates/test` there are files that don't get scaffolded in the `test` step of the initial scaffolding process. Not sure why.

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
