### ISSUE TITLE
PODS with browserify

### ISSUE THREAD

**Issue by knownasilya** [yeoman/generator-ember#216]
If I was to submit a PR for PODS (using [emberate][1]) support with browserify, would you guys work with me to merge that? Especially since we already use `require` in `app.js`.

Maybe along the lines of:

```bash
yo ember
Would you like to use Browserify?
Would you like to use the PODS project structure?
```

Or maybe do all in browserify with no option for concat.. 

[1]: https://www.npmjs.org/package/emberate

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
