### ISSUE TITLE
add support for bootstrap-for-ember?

### ISSUE THREAD

**Issue by kfir124** [yeoman/generator-ember#219]
I think it would be great if in addition to the "would you like to include sass bootstrap?" question we would add "would you like to include bootstrap-for-ember plugin?" i use bootstrap-for-ember(https://github.com/ember-addons/bootstrap-for-ember) in all my projects and wiring it up each time is a bit pain.

we just need to add it to the bower and remove the bootstrap's javascript files and replace them with the bootstrap-for-ember js files.

same thing about FontAwesome its also a must-included feature that people tend to use in their projects

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
