### ISSUE TITLE
Component Uncaught #<error>

### ISSUE THREAD

**Issue by d3Qa** [yeoman/generator-ember#225]
I tried to create a new block component, e.g:

in: `template/components/test-component.hbs`
```
Test-component's content: <div>{{yield}}</div>
```

And to be called:

in: `template/application.hbs`
```
<div id="application_content">
    {{#test-component}}yield content{{/test-component}}
</div>
```

When its compiled using grunt, it produce an __error__ says:

```
Uncaught #<error>
```

The weird thing is when I tried to manually move all templates to be inline in index.html, it works fine. 

Here's the example when it's already precompiled: http://jsfiddle.net/dekaa/wyQ84/, and this is when I moved inline: http://jsfiddle.net/dekaa/LcSSE/

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
