### ISSUE TITLE
plugins.js is empty when building freshly created app

### ISSUE THREAD

**Issue by tkupari** [yeoman/generator-ember#228]
1. create new app with Bootstrap for Sass
2. run grunt build

Resulting dist/scripts/plugins.js is empty.

Am I missing something or is this intended?

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
