### ISSUE TITLE
grunt test fails

### ISSUE THREAD

**Issue by kgish** [yeoman/generator-ember#229]
When I run yo and install generator-ember, grunt test fails with the following error message:
```
Running "mocha:all" (mocha) task
Testing: http://localhost:9000/index.html

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.
````

This is solved if I do the following:
```
cd test
bouwer install
````

It would be nice if this were setup properly as part of the original installation.

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
