### ISSUE TITLE
Empty Route after scaffold a controller

### ISSUE THREAD

**Issue by heat** [yeoman/generator-ember#232]
when scaffold a controller

```
yo ember:controller Bar

```

```coffee
ForcaEmber.Router.map( ->
  
)
```

create with --coffee param

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
