### ISSUE TITLE
Javascript file after scaffold a model

### ISSUE THREAD

**Issue by heat** [yeoman/generator-ember#233]
I started a fresh project with --coffee

when scaffold a Model it's generated javascript model

```
yo ember:model User name:string password:string

```
```javascript
/*global Ember user_model.js */
ForcaEmber.User = DS.Model.extend({
    name: DS.attr('string'),

    password: DS.attr('string')
});

```

and get my router a mess 
```coffee
ForcaEmber.Router.map( ->
  
  @resource('user_model.js', ->
    @resource('user_model.j', path: '/:user_model.j_id', ->
      @route('edit')
    )
    @route('create')
  )
  
)
```

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
