### ISSUE TITLE
How do I utilize the 'grunt test' setup?

### ISSUE THREAD

**Issue by fourq** [yeoman/generator-ember#235]
How do I setup for ember testing using the generated test dir? Currently the structure is:

```
test
--bower_components
--spec
index.html
```

How do I setup mocha tests to test the generated application?

I tried adding the app/scripts/app.js file to to the test/index.html file so that I could reference the ember namespace but that's not working:

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mocha Spec Runner</title>
    <link rel="stylesheet" href="bower_components/mocha/mocha.css">
</head>
<body>
    <div id="mocha"></div>
    <script src="bower_components/mocha/mocha.js"></script>
    <script src="bower_components/ember-mocha-adapter/adapter.js"></script>
    <script>mocha.setup('bdd')</script>
    <script src="bower_components/chai/chai.js"></script>

    <!-- include source files here... -->
    <script src="../app/scripts/app.js"></script> <!-- DEFINES APP NAMESPACE -->

    <script>
      var assert = chai.assert;
      var expect = chai.expect;
      var should = chai.should();

      PastoralActs.rootElement = '#ember-testing'; // ReferenceError: Can't find variable: PastoralActs
      Ember.Test.adapter = Ember.Test.MochaAdapter.create();
      PastoralActs.setupForTesting();
      PastoralActs.injectTestHelpers();
    </script>

    <!-- include spec files here... -->
    <script src="spec/login.js"></script>
</body>
</html>
```

I feel like I'm completely missing the point of the testing setup, or at least I'm hoping that's the case. Could it be that I cannot reference the ../app/scripts/app.js file outside of the testing servers root like this? If so what's the correct approach?

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
