### ISSUE TITLE
Uncaught ReferenceError: chai is not defined (and no bower.json in test)

### ISSUE THREAD

**Issue by fourq** [yeoman/generator-ember#237]
I ran 
```
yo ember --coffee --test-framework=jasmine --karma --skip-install
```

with ember generator version 0.8.5 and it's missing chai:

```
Chrome 37.0.2062 (Mac OS X 10.9.5) ERROR
  Uncaught ReferenceError: chai is not defined
  at /Users/rocky/myemberapp/.tmp/test/support/initializer.js:8
```

here's a pic of my dir structure [screenshot](http://screencast.com/t/sv6iYm8NwDP)

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
