### ISSUE TITLE
Why isn't the spec/test.js transpiled?

### ISSUE THREAD

**Issue by fourq** [yeoman/generator-ember#238]
I ran 
```
yo ember --coffee --karma
```
[screenshot](http://screencast.com/t/BLnhWwnq3S)

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
