### ISSUE TITLE
Deprecation in favor of ember-cli

### ISSUE THREAD

**Issue by zigomir** [yeoman/generator-ember#249]
http://www.ember-cli.com/ is all the rage for building Ember app. Wouldn't it made sense to at least mention in readme file that there is http://www.ember-cli.com/ project that handles things building ember apps?

**Comment by sindresorhus** [comment]
:+1: Makes sense to deprecate. This also no longer has an active maintainer.

// @yeoman/owners

**Comment by fayimora** [comment]
:+1:

**Comment by kevva** [comment]
I'm all for it.

**Comment by passy** [comment]
:+1:

**Comment by Lxrd-AJ** [comment]
I can see that a maintainer @fayimora  has also voted to deprecate it, i am actually currently using it in a project and migrating to ember cli, when should we expect it to be deprecated

**Comment by SBoudrias** [comment]
Deprecation doesn't mean this project will explode and stop working.

It just mean considering there's no active works being done on this generator, and that the ember community have settled on ember-cli, we'll suggest new users to use ember-cli to get more up to date workflow matching what the ember community is doing.

**Comment by arthurvr** [comment]
:+1:

**Comment by sindresorhus** [comment]
Deprecated the repo, readme and npm package. Added a link to this issue from the readme. Feel free to continue discussing migration paths and other things.

-

fyi @stefanpenner @tomdale

**Comment by supergray** [comment]
Thank you sindresor.
