### ISSUE TITLE
Clean up Gruntfile

### ISSUE THREAD

**Issue by mbixby** [yeoman/generator-ember#72]
I think this project could address some sentiments brought up in [this Brunch issue](https://github.com/brunch/brunch/issues/408#issuecomment-8455527), specifically:

> "Ugly & extremely verbose configuration files (gruntfiles).  Compare: [brunch config](https://github.com/paulmillr/brunch-with-chaplin/blob/master/config.coffee) & [yeoman config](https://gist.github.com/paulmillr/3697384)".

Especially newcomers to Ember could be a bit startled by the boilerplate in Gruntfile. Some default configuration could be moved to a separate file in `generator-ember`, leaving only config that is semantically important.

This would be in line with Ember's goals in that it should be easy to pick up / use / understand (as Tom Dale mentioned in [this video](http://vimeo.com/68215606)).

Some additional ideas:
* grunt tasks could be briefly explained so a newbie could immediately understand what they do just by looking in Gruntfile
* generating with option `--coffee` should automatically generate `Gruntfile.coffee` instead of `Gruntfile.js`
* extract helpers like 'mountFolder', move Livereload snippet and Yeoman config inline like in this [Gruntfile](https://gist.github.com/mbixby/5952914)

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
